# Contains entities used for local development
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component
  description: Test component
spec:
  type: repository
  lifecycle: experimental
  owner: user:development/guest
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  title: Guest User
  namespace: development
spec:
  memberOf:
    - group:default/test-group
  profile:
    displayName: Guest User
    email: foobar@foo.com
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe
  title: John Doe
  namespace: development
spec:
  memberOf:
    - group:default/test-group
  profile:
    displayName: John Doe
    email: barfoo@foo.com
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jane.doe
  title: Jane Doe
  namespace: development
spec:
  memberOf:
    - group:default/child-group
  profile:
    displayName: Jane Doe
    email: barfoo@bar.com
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: test-group
  namespace: default
spec:
  type: test-group
  owner: user:development/guest
  members:
    - user:development/guest
    - user:development/john.doe
  children:
    - group:default/child-group
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: child-group
  namespace: default
spec:
  type: child-group
  owner: user:development/jane.doe
  members:
    - user:development/jane.doe
  children: []
