site_name: 'Backstage Q&A plugin'
site_description: 'Q&A for Backstage'

nav:
  - Home: index.md
  - Setup: setup.md
  - Config: config.md
  - Catalog: catalog.md
  - 'Integration with @backstage/plugin-search': search.md

plugins:
  - techdocs-core
