site_name: 'Backstage Q&A plugin'
site_description: 'Q&A for Backstage'

nav:
  - Home: index.md
  - Setup: setup.md
  - Config: config.md
  - Migration Guide: migration.md
  - Extensions: extensions.ms
  - Templates: templates.md
  - AI: ai.md
  - Integrations:
      - Catalog: catalog.md
      - Search: search.md
      - Events: events.md
      - Permissions: permissions.md
      - Notifications: notifications.md
      - Signals: signals.md
      - Home: home.md
  - Translations: translations.md

plugins:
  - techdocs-core
